version: "3"

services:
  # consul-server:
  #   image: consul:latest
  #   command: "consul agent -dev -client=0.0.0.0 -dns-port=53 -recursor=8.8.8.8 -config-file=/etc/consul.d/config.json"
  #   # network_mode: host
  #   ports:
  #     - "8600:8600"
  #     - "8500:8500"
  #     - "8301:8301"
  #     - "8300:8300"
  #     - "53:53"
  #   volumes:
  #     - ./consul/server.d/:/etc/consul.d/

  nomad-server:
    build: ./nomad
    privileged: true
    # network_mode: host
    expose:
      - "4646"
      - "4647"
      - "4648"
    ports:
      - "53:53/udp"
      - "4646:4646"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./nomad/server.d/:/etc/nomad.d/
      - ./consul/client.d/:/etc/consul.d/
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp:/tmp
    # depends_on:
    #   - consul-server

  # just need follower to avoid port 4646 conflict
  # nomad-server-follower:
  #   build: ./nomad
  #   privileged: true
  #   expose:
  #     - "4647"
  #     - "4648"
  #   volumes:
  #     - ./nomad/server.d/:/etc/nomad.d/
  #     - ./consul/client.d/:/etc/consul.d/
  #   depends_on:
  #     - nomad-server

  # nomad-client-dc1:
  #   build: ./nomad
  #   privileged: true
  #   volumes:
  #     - ./nomad/client-dc1.d/:/etc/nomad.d/
  #     - ./consul/client.d/:/etc/consul.d/
  #   depends_on:
  #     - nomad-server

  # nomad-client-dc2:
  #   build: ./nomad
  #   privileged: true
  #   volumes:
  #     - ./nomad/client-dc2.d/:/etc/nomad.d/
  #     - ./consul/client.d/:/etc/consul.d/
  #   depends_on:
  #     - nomad-server
